version: '3.7'

services:
  database:
    container_name: database
    image: postgres:14.4
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker_multiple_databases:/docker-entrypoint-initdb.d
    shm_size: 256mb
    environment:
      POSTGRES_USER: bromles
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: keycloak_db,backend_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    deploy:
      resources:
        limits:
          memory: 512M

  search_engine:
    container_name: search_engine
    image: getmeili/meilisearch:v0.27.2
    volumes:
      - meili_data:/data/meili_data
    depends_on:
      - database
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_NO_ANALYTICS: "true"
    ports:
      - "7123:7700"
    deploy:
      resources:
        limits:
          memory: 512M

  auth_server:
    container_name: auth_server
    image: quay.io/keycloak/keycloak:19.0.3
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: bromles
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: bromles
      KEYCLOAK_ADMIN_PASSWORD: password
    ports:
      - '8099:8080'
    command:
      - start-dev
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - database

  backend:
    container_name: backend
    image: home_library
    environment:
      DB_URL: "jdbc:postgresql://database/backend_db"
      DB_USERNAME: "bromles"
      DB_PASSWORD: "password"
      SEARCH_ENGINE_URL: "http://search_engine:7070"
      SEARCH_ENGINE_KEY: "masterKey"
      AUTH_SERVER_URL: "http://auth_server:8080/auth/realms/master/protocol/openid-connect/certs"
    depends_on:
      - database
      - search_engine
      - auth_server
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G

  frontend:
    container_name: frontend
    build: frontend/web/
    ports:
      - '8123:80'
    depends_on:
      - backend
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  db-data:
  meili_data:
