version: '3.7'

services:
  database:
    container_name: database
    image: postgres:14.4
    volumes:
      - postgres_data:$$(pwd)/data/pgsql
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak_db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  search_engine:
    container_name: search_engine
    image: getmeili/meilisearch:v0.27.2
    volumes:
      - meili_data:$$(pwd)/data/meili_data
    depends_on:
      - database
    deploy:
      resources:
        limits:
          memory: 512M

  auth_server:
    container_name: auth_server
    image: quay.io/keycloak/keycloak:18.0.2
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak_db
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - '8099:8080'
    deploy:
      resources:
        limits:
          memory: 512M
    depends_on:
      - database
    restart: unless-stopped

  backend:
    container_name: backend
    build: backend/
    depends_on:
      - database
      - search_engine
      - auth_server
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    container_name: frontend
    build: frontend/
    ports:
      - '8123:80'
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
  meili_data: