name: Maven CI/CD

on:
  pull_request:
    branches:
      - dev
      - master

jobs:

  e2e_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set volume
        run: sudo sh ./set_volume_from_archive.sh
        shell: bash
      - name: Set java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Rub docker compose
        run: ./run.sh
        shell: bash
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Run Cypress
        uses: cypress-io/github-action@v5
        with:
          working-directory: frontend/web/
          browser: chrome
          record: true
          wait-on: http://localhost:8082, http://localhost:8123, http://localhost:8099
        env:
          CYPRESS_RECORD_KEY: 6247b4f2-11c6-46cd-b4da-518694559bff

